const fs = require('fs');
const files = [
  'src/pages/AdminDashboard.tsx',
  'src/pages/AdminProfilePage.tsx',
  'src/pages/StaffDashboard.tsx',
  'src/pages/SuperAdminDashboard.tsx',
  'src/pages/SuperAdminManagementPage.tsx',
];
const reps = [
  [/inline-flex px-2 py-1 text-xs font-semibold rounded-full/g, 'status-chip cursor-pointer'],
  [/inline-flex px-3 py-1 text-xs font-semibold rounded-full/g, 'status-chip cursor-pointer'],
  [/px-2 py-1 text-xs rounded-full/g, 'status-chip'],
  [/px-3 py-1 text-xs rounded-full/g, 'status-chip'],
  [/bg-green-100 text-green-800 border-green-200/g, 'status-chip status-chip--ok'],
  [/bg-blue-100 text-blue-800/g, 'status-chip status-chip--neutral'],
  [/bg-emerald-100 text-emerald-800/g, 'status-chip status-chip--ok'],
  [/bg-orange-100 text-orange-800/g, 'status-chip status-chip--warn'],
  [/bg-yellow-100 text-yellow-800/g, 'status-chip status-chip--warn'],
  [/bg-red-100 text-red-800/g, 'status-chip status-chip--danger'],
  [/bg-gray-100 text-gray-800/g, 'status-chip status-chip--neutral'],
  [/bg-gray-100 text-ink-soft/g, 'status-chip status-chip--neutral'],
  [/bg-slate-100 text-slate-700/g, 'status-chip status-chip--neutral'],
  [/bg-purple-100 text-purple-800/g, 'status-chip status-chip--warn'],
  [/bg-green-100 text-green-800/g, 'status-chip status-chip--ok'],
  [/bg-gradient-to-r from-emerald-600 to-sky-600 text-white/g, 'bg-ink text-white'],
  [/bg-emerald-600/g, 'bg-forest'],
  [/hover:bg-emerald-700/g, 'hover:bg-forest-deep'],
  [/text-purple-100/g, 'text-white/70'],
  [/text-blue-100/g, 'text-white/70'],
  [/text-yellow-300/g, 'text-brass'],
  [/bg-gradient-to-r from-yellow-400 to-orange-400 rounded-full/g, 'bg-brass rounded-sm'],
  [/bg-blue-600 text-white rounded-sm hover:bg-blue-700/g, 'btn-primary'],
  [/bg-purple-600 text-white rounded-sm hover:bg-purple-700/g, 'btn-primary'],
  [/hover:scale-105/g, ''],
  [/animate-pulse/g, ''],
  [/bg-gradient-to-br from-blue-50 to-purple-50 rounded-xl border border-blue-200/g, 'bg-sand-warm border border-sand-deep rounded-sm'],
  [/bg-blue-50 border border-blue-200/g, 'bg-sand-warm border border-sand-deep'],
  [/bg-green-50 border border-green-200/g, 'bg-accent-50 border border-accent-100'],
  [/border-blue-200 bg-blue-50/g, 'border-sand-deep bg-sand-warm'],
  [/border-green-200 bg-green-50/g, 'border-accent-100 bg-accent-50'],
  [/bg-blue-100 rounded-sm/g, 'bg-sand border border-sand-deep rounded-sm'],
  [/bg-purple-100 rounded-sm/g, 'bg-sand border border-sand-deep rounded-sm'],
  [/bg-green-100 rounded-sm/g, 'bg-accent-50 border border-accent-100 rounded-sm'],
  [/bg-blue-50 rounded-sm/g, 'bg-sand-warm rounded-sm'],
  [/bg-yellow-50 rounded-sm/g, 'bg-sand-warm rounded-sm'],
  [/bg-green-50 rounded-sm/g, 'bg-accent-50 rounded-sm'],
  [/bg-gradient-to-t from-blue-600 to-blue-400/g, 'bg-ink'],
  [/bg-gradient-to-t from-green-600 to-green-400/g, 'bg-forest'],
  [/bg-gradient-to-r from-green-400 via-blue-400 via-yellow-400 to-red-400/g, 'border-8 border-sand-deep bg-sand-warm'],
  [/hover:from-blue-700 hover:to-blue-500/g, 'hover:opacity-90'],
  [/hover:from-green-700 hover:to-green-500/g, 'hover:opacity-90'],
  [/peer-checked:bg-purple-600/g, 'peer-checked:bg-brass'],
  [/peer-focus:ring-purple-300/g, 'peer-focus:ring-brass/30'],
  [/animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600/g, 'animate-spin rounded-full h-8 w-8 border-b-2 border-brass'],
  [/bg-blue-500/g, 'bg-ink'],
  [/bg-green-500/g, 'bg-forest'],
  [/bg-orange-500/g, 'bg-brass'],
  [/bg-yellow-500/g, 'bg-brass'],
  [/bg-yellow-400/g, 'bg-brass'],
  [/bg-green-400/g, 'bg-forest'],
  [/bg-blue-400/g, 'bg-ink-soft'],
  [/text-green-300/g, 'text-accent-100'],
  [/text-blue-300/g, 'text-white/80'],
  [/text-purple-300/g, 'text-brass'],
  [/hover:text-purple-800/g, 'hover:text-brass-deep'],
  [/color: 'bg-red-500'/g, "color: 'bg-red-700'"],
  [/color: 'bg-orange-500'/g, "color: 'bg-brass'"],
  [/color: 'bg-yellow-500'/g, "color: 'bg-brass-deep'"],
  [/color: 'bg-blue-500'/g, "color: 'bg-ink-soft'"],
  [/color: 'bg-green-500'/g, "color: 'bg-forest'"],
  [/text-gray-400/g, 'text-ink-muted'],
  [/text-gray-800/g, 'text-ink'],
];

for (const file of files) {
  let c = fs.readFileSync(file, 'utf8');
  for (const [from, to] of reps) c = c.replace(from, to);
  fs.writeFileSync(file, c);
}
console.log('pass2 done');
